-- This query will display the current date

SELECT SYSDATE FROM DUAL;

DROP TABLE LocationEtoile CASCADE CONSTRAINTS;
DROP TABLE FilmEtoile;
DROP TABLE ClientEtoile;
DROP TABLE TempsEtoile;



CREATE TABLE FilmEtoile
(Film_ID INTEGER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
Titre VARCHAR(100),
Annee INTEGER,
Origine VARCHAR(10),
Fantasy NUMBER(1) DEFAULT 0 NOT NULL,
Animation NUMBER(1) DEFAULT 0 NOT NULL,
Adventure NUMBER(1) DEFAULT 0 NOT NULL,
Western NUMBER(1) DEFAULT 0 NOT NULL,
Comedy NUMBER(1) DEFAULT 0 NOT NULL,
Musical NUMBER(1) DEFAULT 0 NOT NULL,
Documentary NUMBER(1) DEFAULT 0 NOT NULL,
Film-Noir NUMBER(1) DEFAULT 0 NOT NULL,
Biography NUMBER(1) DEFAULT 0 NOT NULL,
War NUMBER(1) DEFAULT 0 NOT NULL,
Crime NUMBER(1) DEFAULT 0 NOT NULL,
Mystery NUMBER(1) DEFAULT 0 NOT NULL,
Thriller NUMBER(1) DEFAULT 0 NOT NULL,
Drama NUMBER(1) DEFAULT 0 NOT NULL,
Sport NUMBER(1) DEFAULT 0 NOT NULL,
Horror NUMBER(1) DEFAULT 0 NOT NULL,
Music NUMBER(1) DEFAULT 0 NOT NULL,
Family NUMBER(1) DEFAULT 0 NOT NULL,
Romance NUMBER(1) DEFAULT 0 NOT NULL,
History NUMBER(1) DEFAULT 0 NOT NULL,
Action NUMBER(1) DEFAULT 0 NOT NULL,
Sci-Fi NUMBER(1) DEFAULT 0 NOT NULL,
PRIMARY KEY(Film_ID));

CREATE TABLE ClientEtoile
(Client_ID INTEGER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
Nom VARCHAR(100),
Prenom VARCHAR(100),
Groupe_Age INTEGER,
Aciennete TIMESTAMP,
Code_Postal VARCHAR(20),
Ville VARCHAR(50),
Province VARCHAR(50),
PRIMARY KEY(Client_ID));

CREATE TABLE TempsEtoile
(Temps_ID INTEGER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
Heure INTEGER,
Jour_Mois INTEGER,
Jour_Semaine INTEGER,
Mois INTEGER,
Annee INTEGER,
PRIMARY KEY(Temps_ID));

CREATE TABLE LocationEtoile(
Film_ID INTEGER,
Client_ID INTEGER,
Temps_ID INTEGER,
PRIMARY KEY(Film_ID, Client_ID, Temps_ID));
/
ALTER TABLE LocationEtoile
ADD (
CONSTRAINT FK_Film_ID
FOREIGN KEY (Film_ID) REFERENCES FilmEtoile(Film_ID),

CONSTRAINT FK_Client_ID
FOREIGN KEY (Client_ID) REFERENCES ClientEtoile(Client_ID),

CONSTRAINT FK_Temps_ID
FOREIGN KEY (Temps_ID) REFERENCES TempsEtoile(Temps_ID)
);
